"""db init

Revision ID: 023907b9a768
Revises: 
Create Date: 2021-06-09 22:23:26.640097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023907b9a768'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('surname', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('terrorist', sa.Boolean(), nullable=False),
    sa.Column('criminal_record', sa.Boolean(), nullable=False),
    sa.Column('mental_health', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
